mongo:
    build: mongo
    ports:
        - "4202:27017"
    volumes:
            - "./mongo/data:/data/db"

web_server:
    build: web_server
    ports:
        - "4201:4201"
        - "3042:3042"
    volumes:
            - "./web_server/app:/src/app"
    links:
            - mongo:mongo

web_client:
    image: nginx
    ports:
        - "80:80"
    volumes:
            - "./web_client:/usr/share/nginx/html"

mail_dev:
    image : djfarrelly/maildev
    ports:
        - "4242:80"
        - "4203:25"